data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: echo
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: echo-http
  namespace: default
  annotations:
    osiris.deislabs.io/deployment: "echo-http"
    osiris.deislabs.io/enabled: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: echo-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerSourceRanges:
  - {.loadBalancerSourceRange}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-http
  namespace: default
  labels:
    app: echo-http
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/minReplicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-http
  template:
    metadata:
      labels:
        app: echo-http
    spec:
      containers:
      - name: echo-http
        image: hannesn/echo
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: Echo
        envFrom:
        - secretRef:
            name: echo
---

